[build]
  base = "client/"
  command = "npm run build"
  functions = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  node_bundler = "esbuild"

[[env]]
MAPBOX_API_KEY = "pk.eyJ1IjoiYW5uYW5kb2JvdCIsImEiOiJjbGRrdTdqcjMxNTg1M3Bub2lqMngzbDRkIn0.nyR4LZlj_13g9Oxr6yckNQ"
YELP_API_KEY = "Oi7OKS98tHDYsPkdEv5wUt96WcLjAr204iQDUiZOvVkCo7-DnhDjOZhXqdk6BiD23EJ6tEI3EhyrFw5gTklbQfpp541RUEvb1vz9qx58tAGBWV_ilQGvcPHoyhDYY3Yx"
GOOGLE_API_KEY = "AIzaSyBJgNjz5kWcXnG-ZfN6VYHASoBLocwPf8k"
