[build]
  base = "client/"
  command = "npm run build"
  functions = "netlify/functions"
  publish = "public"

[functions]
  node_bundler = "esbuild" 

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
